from django.conf.urls import  url
from django.contrib import admin
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^home$','cmubbs.views.home',name='cmu_home'),
    url(r'^$','cmubbs.views.intro',name='intro'),
    url(r'^nav_login$', 'cmubbs.views.user_login', name='nav_login'),
    url(r'^logout$', 'cmubbs.views.user_logout', name='logout'),
    url(r'^register$', 'cmubbs.views.user_register', name='register'),
    url(r'^change_password$', 'django.contrib.auth.views.password_change', {'template_name':'userauth/change_password.html','post_change_redirect' : 'user_profile','password_change_form': AdminPasswordChangeForm},name='change_password'),
    url(r'^edit_profile$', 'cmubbs.views.edit_profile', name='edit_profile'),
    url(r'^profile_photo/(?P<userid>.+)$', 'cmubbs.views.get_profile_photo', name="profile_photo"),
    url(r'^manage_forums$', 'cmubbs.views.manage_forums', name="manage_forums"),
    url(r'^add_sub_forum/(?P<father_forum_name>|.+)$', 'cmubbs.views.add_sub_forum', name="add_sub_forum"),
    url(r'^delete_forum/(?P<forum_name>|.+)$', 'cmubbs.views.delete_forum', name="delete_forum"),
    url(r'^edit_forum/(?P<forum_name>|.+)$', 'cmubbs.views.edit_forum', name="edit_forum"),
    url(r'^edit_moderator/(?P<forum_name>|.+)$', 'cmubbs.views.edit_moderator', name="edit_moderator"),
    url(r'^delete_moderator/(?P<forum_name>|.+)/(?P<userid>.+)$', 'cmubbs.views.delete_moderator', name="delete_moderator"),
    url(r'^add_father_forum$', 'cmubbs.views.add_father_forum', name="add_father_forum"), 
    url(r'^hot$','cmubbs.views.hot_topics',name='hot_topics'),
    url(r'^messages_main$','cmubbs.views.get_all_messages',name='get_all_messages'),
    url(r'^messages_thread/(?P<friend_name>.+)$','cmubbs.views.get_messages_with',name='get_messages_with'),
    url(r'^get_notifications$','cmubbs.views.get_notifications',name='get_notifications'),
    url(r'^sub_forum/(?P<father_forum_name>|.+)$','cmubbs.views.sub_forum',name='sub_forum'),
    url(r'^in_forum/(?P<forum_name>|.+)$','cmubbs.views.in_forum',name='in_forum'),
    url(r'^favorite_forum/(?P<forum_name>|.+)$','cmubbs.views.favorite_forum',name='favorite_forum'),
    url(r'^dislike_forum/(?P<forum_name>|.+)$','cmubbs.views.dislike_forum',name='dislike_forum'),
    url(r'^in_topic/(?P<topic_id>|.+)$','cmubbs.views.in_topic',name='in_topic'),
    url(r'^reset_password$', 'django.contrib.auth.views.password_reset',
        {'template_name':'userauth/reset_password.html', 
         'post_reset_redirect' : 'reset_password_done',
         'email_template_name' : 'userauth/reset_password_email.html'}, name="reset_password"),
    url(r'^reset_password_done$', 'django.contrib.auth.views.password_reset_done', {'template_name':'userauth/reset_password_done.html'}, name="reset_password_done"),
    url(r'^reset_password/(?P<uidb64>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm', 
        {'template_name':'userauth/reset_password_confirm.html',
         'post_reset_redirect' : 'reset_password_complete'}, 
        name="reset_password_confirm"),
    url(r'^reset_password_complete$', 'django.contrib.auth.views.password_reset_complete', {'template_name':'userauth/reset_password_complete.html'}, name="reset_password_complete"),
    url(r'^new_post/(?P<forum_name>.+)$','cmubbs.views.new_post', name='new_post'),
    url(r'^new_poll/(?P<forum_name>.+)$','cmubbs.views.new_poll', name='new_poll'),
    url(r'^create_event/(?P<forum_name>.+)$','cmubbs.views.create_event', name='create_event'),
    url(r'^load_events/(?P<forum_name>.+)$','cmubbs.views.load_events', name='load_events'),
    url(r'^like_topic/(?P<topic_id>.+)$','cmubbs.views.like_topic', name='like_topic'),
    url(r'^dislike_topic/(?P<topic_id>.+)$','cmubbs.views.dislike_topic', name='dislike_topic'),
    url(r'^up_topic/(?P<topic_id>.+)$','cmubbs.views.up_topic', name='up_topic'),
    url(r'^down_topic/(?P<topic_id>.+)$','cmubbs.views.down_topic', name='down_topic'),
    url(r'^good_topic/(?P<topic_id>.+)$','cmubbs.views.good_topic', name='good_topic'),
    url(r'^normal_topic/(?P<topic_id>.+)$','cmubbs.views.normal_topic', name='normal_topic'),
    url(r'^user_profile/(?P<user_name>|.+)$','cmubbs.views.user_profile', name='user_profile'),
    url(r'^user_profile$','cmubbs.views.user_profile', name='user_profile'),
    url(r'^get_user_info/(?P<user_name>|.+)$','cmubbs.views.get_user_info', name='get_user_info'),
    url(r'^search_topic$','cmubbs.views.search_topic', name='search_topic'),
    url(r'^search_topic/(?P<forum_name>.+)$','cmubbs.views.search_topic', name='search_topic'),
    url(r'^delete_topic/(?P<forum_name>|.+)/(?P<topic_id>.+)/(?P<page_num>.+)/(?P<filter_tag>.+)$','cmubbs.views.delete_topic', name='delete_topic'),
    url(r'^reply_comment$', 'cmubbs.views.reply_comment', name='reply_comment'),
    url(r'^advanced_search/(?P<forum_id>|.+)$', 'cmubbs.views.advanced_search', name='advanced_search'),
    url(r'^back_to_forum/(?P<forum_id>|.+)$', 'cmubbs.views.back_to_forum', name='back_to_forum'),
    url(r'^user_own_events/(?P<userid>.+)$', 'cmubbs.views.user_own_events', name="user_own_events"),
    url(r'^user_participating_events/(?P<userid>.+)$', 'cmubbs.views.user_participating_events', name="user_participating_events"),
    url(r'^user_event_applications$', 'cmubbs.views.user_event_applications', name="user_event_applications"),
    url(r'^edit_event/(?P<topic_id>|.+)$','cmubbs.views.edit_event',name='edit_event'),
    url(r'^add_participant/(?P<topic_id>|.+)$', 'cmubbs.views.add_participant', name="add_participant"),
    url(r'^delete_participant/(?P<topic_id>|.+)/(?P<userid>.+)$', 'cmubbs.views.delete_participant', name="delete_participant"),
    url(r'^rsvp_event/(?P<topic_id>|.+)$','cmubbs.views.rsvp_event',name='rsvp_event'),
    url(r'^apply_for_event/(?P<topic_id>|.+)$','cmubbs.views.apply_for_event',name='apply_for_event'),
    url(r'^undo_rsvp_event/(?P<topic_id>|.+)$','cmubbs.views.undo_rsvp_event',name='undo_rsvp_event'),
    url(r'^post_images/(?P<image_id>|.+)$','cmubbs.views.post_images',name='post_images'),
    url(r'^upload_usr_image$', 'cmubbs.views.upload_usr_image', name='upload_usr_image'),
    url(r'^vote/(?P<topic_id>|.+)$', 'cmubbs.views.vote', name='vote'),
    url(r'^accept_event_application/(?P<application_id>|.+)$', 'cmubbs.views.accept_event_application', name='accept_event_application'),
    url(r'^decline_event_application/(?P<application_id>|.+)$', 'cmubbs.views.decline_event_application', name='decline_event_application'),
    url(r'^follow/(?P<user_name>.+)$', 'cmubbs.views.follow', name='follow'),
    url(r'^unfollow/(?P<user_name>.+)$', 'cmubbs.views.unfollow', name='unfollow'),
    url(r'^collections$','cmubbs.views.collections', name='collections'),
    url(r'^activities/(?P<user_name>.+)$','cmubbs.views.activities', name='activities'),
    url(r'^self_topics/(?P<user_name>.+)$','cmubbs.views.self_topics', name='self_topics'),
    url(r'^show_follow/(?P<username>|.+)/(?P<type_id>.+)','cmubbs.views.show_follow', name='show_follow'),
    url(r'^add_sub_post/(?P<topic_id>.+)$', 'cmubbs.views.add_sub_post', name='add_sub_post'),
    url(r'^remove_notifications/(?P<id>.+)$', 'cmubbs.views.remove_notifications', name='remove_notifications'),
    url(r'^preview_post$','cmubbs.views.preview_post', name='preview_post'),

]



